name: flutter_advanced_drawer_example
description: Demonstrates how to use the flutter_advanced_drawer plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 3.7.3

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_drawer:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/images/
